def throw_exception():
    raise Exception()
